version: "3.7"
services:
 database:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   ports:
      - "3307:3306"
 redis:
   image: redis:latest
 website:
   links:
      - elasticsearch
      - database
      - redis
      - sidekiq
   build: .
   ports:
      - "3000:3000"
   environment:
     DB_USERNAME: root
     ELASTICSEARCH_HOST: elasticsearch
     DB_PASSWORD: root
     DB_DATABASE: ChatBackEnd
     DB_PORT: 3306
     working_dir: /app
     REDIS_URL_SIDEKIQ: redis://redis:6379/1
     JOB_WORKER_URL: redis://redis:6379/0
     DB_HOST: database
     RAILS_ENV: development
     RAILS_MAX_THREADS: 50
   volumes:
      - ".:/app"
      - "./config/docker/database.yml:/app/config/database.yml"

 sidekiq:
   build: .
   depends_on: 
      - database
      - redis
   volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
   environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     ELASTICSEARCH_HOST: elasticsearch
     DB_DATABASE: ChatBackEnd
     DB_PORT: 3306
     working_dir: /app
     REDIS_URL_SIDEKIQ: redis://redis:6379/1
     JOB_WORKER_URL: redis://redis:6379/0
     DB_HOST: database
     RAILS_ENV: development
     RAILS_MAX_THREADS: 50
   entrypoint: ./entrypoints/sidekiq-entrypoint.sh

 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
   hostname: elasticsearch
   environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
   ports:
      - "9200:9200"
      - "9300:9300"
   volumes:
      - elasticsearch22:/usr/share/elasticsearch/data
   links: 
      - database
volumes:
 redis:
 database:
 gem_cache:
 node_modules:
 elasticsearch22: